# Generated by Django 2.1.5 on 2019-03-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_order',
            field=models.CharField(blank=True, max_length=40, verbose_name='id заказа'),
        ),
    ]
