# Generated by Django 2.1.5 on 2019-02-26 15:30

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionsCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Состав коллекции',
                'verbose_name': 'Состав коллекции',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=10, verbose_name='Артикул')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products', verbose_name='Картинка товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Высота, см')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ширина, см')),
                ('col_in_upac', models.PositiveIntegerField(verbose_name='Кол-во в упаковке')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь в упаковке')),
                ('stock', models.PositiveIntegerField(verbose_name='В наличии шт')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('novinka', models.BooleanField(default=True, verbose_name='Новинка')),
                ('sale', models.BooleanField(default=True, verbose_name='Распродажа')),
                ('hits', models.PositiveIntegerField(default=0, null=True, verbose_name='Количество продаж')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Цвет')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Цвета',
                'verbose_name': 'Цвет',
            },
        ),
        migrations.CreateModel(
            name='ProductCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Страна')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Страны',
                'verbose_name': 'Страна',
            },
        ),
        migrations.CreateModel(
            name='ProductProizvoditel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Производитель')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('productcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.ProductCountry', verbose_name='Страна')),
            ],
            options={
                'verbose_name_plural': 'Производители',
                'verbose_name': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Тип плитки')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Типы плитки',
                'verbose_name': 'Тип плитки',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeSurface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Тип поверхности')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Типы поверхности',
                'verbose_name': 'Тип поверхности',
            },
        ),
        migrations.CreateModel(
            name='ProductСollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Коллекция')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='collections', verbose_name='Картинка коллекции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна к публикации')),
                ('productcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.ProductCategory', verbose_name='Категория')),
                ('productproizvoditel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.ProductProizvoditel', verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'Коллекции',
                'verbose_name': 'Коллекции',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.ProductCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='productcategory', on_delete=django.db.models.deletion.CASCADE, to='productsapp.ProductСollection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.ProductColor', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='copmositions',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='collection', chained_model_field='collection', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productsapp.CompositionsCollection', verbose_name='Входит в состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='surface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.ProductTypeSurface', verbose_name='Тип поверхности'),
        ),
        migrations.AddField(
            model_name='product',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.ProductType', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='compositionscollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productsapp.ProductСollection'),
        ),
    ]
