# Generated by Django 2.1.5 on 2019-03-02 10:04

from django.db import migrations, models
import productsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_auto_20190301_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=productsapp.models.get_file_path_products, verbose_name='Картинка товара'),
        ),
        migrations.AlterField(
            model_name='productсollection',
            name='image',
            field=models.ImageField(blank=True, upload_to=productsapp.models.get_file_path_collect, verbose_name='Картинка коллекции'),
        ),
    ]
