# Generated by Django 2.1.5 on 2019-03-07 12:31

from django.db import migrations, models
import django.db.models.deletion
import productsapp.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_auto_20190302_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='novinka',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.AddField(
            model_name='productproizvoditel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='productproizvoditel',
            name='image',
            field=models.ImageField(blank=True, upload_to=productsapp.models.get_file_path_proizvoditel, verbose_name='Логотип производителя'),
        ),
        migrations.AddField(
            model_name='productсollection',
            name='novinka',
            field=models.BooleanField(default=True, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='productсollection',
            name='sale',
            field=models.BooleanField(default=True, verbose_name='Распродажа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='productcategory', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='productsapp.ProductСollection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='copmositions',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='collection', chained_model_field='collection', on_delete=django.db.models.deletion.CASCADE, related_name='items', show_all=True, to='productsapp.CompositionsCollection', verbose_name='Входит в состав'),
        ),
    ]
